---
name: PurePermsScore-PM5
main: Ifera\PurePermsScore\Main
api: 5.0.0
version: 2.0.0
author: Ifera, rydevs29
description: A plugin implementing some basic tags for ScoreHud.
depend:
- ScoreHud
- PurePerms
...
